env:
  browser: true
  es2020: true
  node: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
  project: './tsconfig.json'
settings:
  react:
    version: detect
plugins:
  - react
  - '@typescript-eslint'
rules: {
    no-unused-vars: 'off',
    react/jsx-uses-react: 'off', # https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint
    react/react-in-jsx-scope: 'off', # https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint
  }
