name: 🚀 Build and deploy to Hostinger 🚀
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build_n_deploy:
    name: 🚚 Deploy 🚚
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🔨 Install dependencies & Build
        run: |
          npm install
          npm run build
      - name: 📂 Hostinger FTP transfer 📂
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.larshansen.dev
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: ./build/
          log-level: standard # warn(?), standard, verbose
          # state-name: #set path & filename
          # dry-run: true
          # Explanation server-dir: using './' created '/publicFolder/publicFolder/[build]'.
          # Likely cuz of the FTP account's directory settings in Hostinger
          server-dir: ../
